version: '3'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  redis:
    image: 'redis/redis-stack:edge'
    ports:
      - '6379:6379'
    environment:
      - 'REDIS_ARGS=--appendonly yes'
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  redis-data:
